[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-monovedek_lcars
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-monovedek_lcars
GtkTheme=oomox-monovedek_lcars
IconTheme=oomox-monovedek_lcars
MetacityTheme=oomox-monovedek_lcars
